# Generated by Django 5.0.3 on 2024-03-09 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/cities_images')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('stars', models.PositiveSmallIntegerField(choices=[(2, 'دو ستاره'), (3, 'سه ستاره'), (4, 'چهار ستاره'), (5, 'پنج ستاره')])),
                ('address', models.CharField(max_length=150)),
                ('free_parking', models.BooleanField(default=False)),
                ('free_net', models.BooleanField(default=False)),
                ('ATM', models.BooleanField(default=True)),
                ('elevator', models.BooleanField(default=True)),
                ('newspaper', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('shop', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('prayer_room', models.BooleanField(default=False)),
                ('marriage_room', models.BooleanField(default=False)),
                ('barbers', models.BooleanField(default=False)),
                ('safe_box', models.BooleanField(default=False)),
                ('lobby', models.BooleanField(default=False)),
                ('lobby_tiolet', models.BooleanField(default=False)),
                ('coffee_shop', models.BooleanField(default=False)),
                ('resturant', models.BooleanField(default=True)),
                ('breakfast_room', models.BooleanField(default=False)),
                ('traditional_teahouse', models.BooleanField(default=False)),
                ('conference_hall', models.BooleanField(default=False)),
                ('green_space', models.BooleanField(default=False)),
                ('tennis_court', models.BooleanField(default=False)),
                ('view', models.CharField(blank=True, max_length=15, null=True)),
                ('english_language_employees', models.BooleanField(default=False)),
                ('lobby_sofa', models.BooleanField(default=True)),
                ('room_service', models.BooleanField(default=False)),
                ('laundry', models.BooleanField(default=False)),
                ('be_awake', models.BooleanField(default=False)),
                ('medical_services', models.BooleanField(default=False)),
                ('show_wax', models.BooleanField(default=False)),
                ('breakfast_in_room', models.BooleanField(default=False)),
                ('lunch_in_room', models.BooleanField(default=False)),
                ('fax', models.BooleanField(default=False)),
                ('photocopy', models.BooleanField(default=False)),
                ('luggage_room', models.BooleanField(default=False)),
                ('travel_agency', models.BooleanField(default=False)),
                ('freight_services', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/hotels_images')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='hotels.city')),
            ],
        ),
        migrations.CreateModel(
            name='HotelComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hotels.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/hotels_images')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('capacity', models.CharField(max_length=50)),
                ('breakfast', models.CharField(choices=[('سرد', 'سرد'), ('گرم', 'گرم'), ('سرد و گرم', 'سرد و گرم')], max_length=30)),
                ('room_number', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotels.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotels.room')),
            ],
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_likes', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='hotels.hotelcomment')),
            ],
            options={
                'unique_together': {('comment', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CommentDisLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_dislikes', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='hotels.hotelcomment')),
            ],
            options={
                'unique_together': {('comment', 'user')},
            },
        ),
        migrations.CreateModel(
            name='HotelLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='hotels.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'hotel')},
            },
        ),
        migrations.CreateModel(
            name='HotelRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='hotels.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('hotel', 'user')},
            },
        ),
    ]
