# Generated by Django 5.0.3 on 2024-03-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_rename_show_wax_hotel_shoe_wax_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='telephone_number',
            field=models.CharField(default=1222234, max_length=20),
            preserve_default=False,
        ),
    ]
